### ISSUE TITLE
ESET NOD32 Antivirus: threat alert

### ISSUE THREAD

**Issue by sitypop** [thlorenz/redeyed#18] opened 2016-10-26 10:50 UTC
<img width="516" alt="screen shot 2016-10-26 at 11 48 36" src="https://cloud.githubusercontent.com/assets/15956596/19723243/3b1c1b60-9b72-11e6-9b52-0da30b51d14c.png">

Any ideas what this means?

Thank you.

**Comment by KKSzymanowski** [comment] 2016-10-26 12:46
Same for me after updating ESET from v9 to v10.

The monit is in Polish but it translates to:
Name: C:\Users\Jakub\AppData\Local\Yarn\cache\npm-redeyed-1.0.0\examples\browser\index.html
Threat: HTML/Scrinject.B trojan horse
Link to threat: http://www.virusradar.com/en/HTML_ScrInject.B/description

VirusTotal however detects the threat only using ESET. [Link to analisys](https://www.virustotal.com/pl/file/41201d7e99512558b75594729b177312ccc5cc9d07d0e415ed287de470b5328e/analysis/1477485495/)

I'm using version 1.0.0.
After removing [this ](https://github.com/thlorenz/redeyed/blob/v1.0.0/examples/browser/index.html#L30) line:
```html
<script type="text/javascript" src="http://esprima.org/esprima.js"></script>
```
ESET says the file is fine.
Also replacing same line with the [corresponding line from master branch](https://github.com/thlorenz/redeyed/blob/master/examples/browser/index.html#L30) makes the file safe according to antivirus.

**Comment by wouter2203** [comment] 2016-10-26 14:22
http://esprima.org/ seems to be on some sort of blacklist.

![image](https://cloud.githubusercontent.com/assets/8761962/19729744/5175ada6-9b98-11e6-9d4b-6fe5ed976e93.png)

The above translates to:

Access to this website is prohibited.

**Comment by KKSzymanowski** [comment] 2016-10-26 15:19
@wouter2203 Yup, just checked, same for me.

**Comment by thlorenz** [comment] 2016-10-26 15:57
This is an ESET issue afaik. See my comment in the duplicate of this issue [here](https://github.com/thlorenz/redeyed/issues/19#issuecomment-256393341).

Gonna close as not a redeyed issue as there are two options:

- a) ESET overreacting (ESET needs to fix)
- b) npm got compromised and the redeyed package tampered with (npm needs to fix)

**Comment by thlorenz** [comment] 2016-10-26 16:10
What @KKSzymanowski stated [here](https://github.com/thlorenz/redeyed/issues/18#issuecomment-256336268) confirms the suspicion that ESET just somehow decided to blacklist _esprima_ which causes all these problems for you guys.
Sorry about that, but they need to fix it .. pretty clear at this point that not a redeyed issue (nor esprima) at all. Therefore closing.

Feel free to keep commenting here if you wanna collect more data.

**Closed by thlorenz** 2016-10-26 16:10 UTC

**Comment by ashclarke** [comment] 2016-10-26 16:40
Would it be worth having a 1.0.1 release with the unpkg link replacing the esprima link in the example page?

**Comment by wouter2203** [comment] 2016-10-26 16:50
@ashclarke I'd say it is.

I understand it's not the plugin authors fault ESET is giving a warning when installing this package, but when it's fixable by a simple fix like that I recommend you implement it to prevent people from opening issues similar to this one.

`<script src="https://unpkg.com/esprima@~3.1/dist/esprima.js"></script>` is what esprima recommends.

**Comment by ashclarke** [comment] 2016-10-26 16:55
@wouter2203 Yeah it's like the butterfly effect all over again. ESET fluttered its wings and potentially broke a bunch of npm packages.

WRT the fix, it's already been done on their master branch @ 6514c52bc1a6927489af1e043a07a73a3a64566f  :)

**Comment by thlorenz** [comment] 2016-10-26 17:53
Would it be worth having a 1.0.1 release with the unpkg link replacing the esprima link in the example page?

@ashclarke no .. not starting to work around bugs in some anti-virus and break the example.

**Comment by thlorenz** [comment] 2016-10-26 17:54
> WRT the fix, it's already been done on their master branch 

Well in that case I can push a patch

**Comment by thlorenz** [comment] 2016-10-26 17:55
Published 1.0.1 (even though that ESET thing is the real culprit)

**Comment by ashclarke** [comment] 2016-10-26 18:01
Completely agree! Wouldn't have suggested it if it wasn't something already
there 😁

**Comment by valera-rozuvan** [comment] 2016-10-26 20:55
@thlorenz Thanks for `1.0.1`! +1
